name: Security Veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * MON-FRI"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          node-version: lts/*

      - name: Install dependencies
        run: npm run setup

      - name: Build
        run: npm run build

      - name: Package
        run: cd dist && zip -r ../source.zip .

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build-results
          path: source.zip

  security-veracode-pipeline-scan:
    name: Security Veracode pipeline scan
    needs: [build]
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@0eaf271d3179fb9946d49f3c02343e26342c159d # v2.21.3
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      veracode_package_artifact_name: build-results
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
      HMPPS_VERACODE_API_ID_0: ${{ secrets.HMPPS_VERACODE_API_ID_0 }}
      HMPPS_VERACODE_API_ID_1: ${{ secrets.HMPPS_VERACODE_API_ID_1 }}
      HMPPS_VERACODE_API_ID_2: ${{ secrets.HMPPS_VERACODE_API_ID_2 }}
      HMPPS_VERACODE_API_ID_3: ${{ secrets.HMPPS_VERACODE_API_ID_3 }}
      HMPPS_VERACODE_API_ID_4: ${{ secrets.HMPPS_VERACODE_API_ID_4 }}
      HMPPS_VERACODE_API_KEY_0: ${{ secrets.HMPPS_VERACODE_API_KEY_0 }}
      HMPPS_VERACODE_API_KEY_1: ${{ secrets.HMPPS_VERACODE_API_KEY_1 }}
      HMPPS_VERACODE_API_KEY_2: ${{ secrets.HMPPS_VERACODE_API_KEY_2 }}
      HMPPS_VERACODE_API_KEY_3: ${{ secrets.HMPPS_VERACODE_API_KEY_3 }}
      HMPPS_VERACODE_API_KEY_4: ${{ secrets.HMPPS_VERACODE_API_KEY_4 }}
